name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Hey there! Thank you very much for contributing to our project. Please make sure to read and accept the CLA before you open the pull request. See [Contributor License Agreement](/CONTRIBUTOR_LICENSE_AGREEMENT.md).'
